steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull ${_IMAGE_URL}:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_IMAGE_URL}:${SHORT_SHA}',
    '--cache-from',
    '${_IMAGE_URL}:latest',
    '-f',
    'Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'tag',
    '${_IMAGE_URL}:${SHORT_SHA}',
    '${_IMAGE_URL}:latest'
  ]

images:
- '${_IMAGE_URL}:${SHORT_SHA}'
- '${_IMAGE_URL}:latest'
substitutions:
  _DOCKER_REGISTRY: 'europe-west3-docker.pkg.dev'
  _IMAGE_NAME: 'chartgpt-app'
  _IMAGE_URL: '${_DOCKER_REGISTRY}/${PROJECT_ID}/${PROJECT_ID}/${_IMAGE_NAME}'
  _IMAGE_TAG: 'latest'
options:
  dynamicSubstitutions: true
