# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates charts and SQL queries based on natural language questions.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.chart.post import ApiChartGenerateChart
from openapi_client.paths.sql.post import ApiSqlGenerateSql


class DefaultApi(
    ApiChartGenerateChart,
    ApiSqlGenerateSql,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
