# Development
start: start_discord_bot start_slack_bot start_telegram_bot

start_discord_bot:
	python -m discord.bot

start_slack_bot:
	python -m slack.bot

start_telegram_bot:
	python -m telegram.bot
