# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates insights from data based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import chartgpt_client
from chartgpt_client.models.output_type import OutputType  # noqa: E501
from chartgpt_client.rest import ApiException

class TestOutputType(unittest.TestCase):
    """OutputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutputType(self):
        """Test OutputType"""
        # inst = OutputType()

if __name__ == '__main__':
    unittest.main()
