import streamlit as st
from firebase_admin import firestore
import plotly.io as pio
import app
from app.components.sidebar import Sidebar
from app.utils import open_page, copy_url_to_clipboard
from app.auth import check_password


# Check basic auth
if not check_password():
    st.stop()

# Display app name
PAGE_NAME = "Chart Gallery"
# st.set_page_config(page_title=PAGE_NAME, page_icon="🎨")
st.markdown("# " + PAGE_NAME + " 🎨")
st.markdown("### Latest 10 charts generated by users of ChartGPT")

# Initialise Streamlit components
sidebar = Sidebar()

# Create a Plotly facet chart with two charts per line of all charts from Firestore
db_charts = app.db.collection('charts')
charts = db_charts.order_by("timestamp", direction=firestore.Query.DESCENDING).limit(10).stream()

# Display all charts
for chart in charts:
    st.markdown(f"#### {chart.get('query_metadata')['query']}")
    st.markdown(f"Dataset: `{chart.get('query_metadata')['dataset_id']}`")
    # st.markdown(f"Timestamp: {chart.get('timestamp')}")
    # st.button('Share chart', type="primary", key=chart.id, on_click=(lambda url=f"/?chart_id={chart.id}": open_page(url)))
    st.button('Copy chart URL', type="primary", key=chart.id, on_click=copy_url_to_clipboard, args=(f"/?chart_id={chart.id}",))
    
    chart_json = chart.to_dict()["json"]
    fig = pio.from_json(chart_json)
    st.plotly_chart(fig, use_container_width=True)
