# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates charts and SQL queries based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import datetime
import unittest

import chartgpt_client
from chartgpt_client.models.api_chart_generate_chart200_response import \
    ApiChartGenerateChart200Response  # noqa: E501
from chartgpt_client.rest import ApiException


class TestApiChartGenerateChart200Response(unittest.TestCase):
    """ApiChartGenerateChart200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiChartGenerateChart200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ApiChartGenerateChart200Response`
        """
        model = chartgpt_client.models.api_chart_generate_chart200_response.ApiChartGenerateChart200Response()  # noqa: E501
        if include_optional :
            return ApiChartGenerateChart200Response(
                description = '', 
                query = '', 
                code = '', 
                chart = '', 
                output = '', 
                dataframe = ''
            )
        else :
            return ApiChartGenerateChart200Response(
        )
        """

    def testApiChartGenerateChart200Response(self):
        """Test ApiChartGenerateChart200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
