# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates insights from data based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import chartgpt_client
from chartgpt_client.models.request import Request  # noqa: E501
from chartgpt_client.rest import ApiException

class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Request`
        """
        model = chartgpt_client.models.request.Request()  # noqa: E501
        if include_optional :
            return Request(
                messages = [
                    chartgpt_client.models.request_messages_inner.Request_messages_inner(
                        id = '', 
                        created_at = 56, 
                        content = '', 
                        role = 'system', )
                    ], 
                data_source_url = 'iotgs/v2D2ylmgd10Z3UB6UkJSISSB512iz/DiJykO4IVP7YNsKQHh9BsaMPOiOuo3_QLOpkBmKIPOf2Flbsh1TpRS00PDvgoKGNXgxLHoPJE-_eV/JNcY9CLxYxBbcfSJXXZ', 
                output_type = 'any', 
                max_outputs = 56, 
                max_attempts = 56, 
                max_tokens = 56
            )
        else :
            return Request(
        )
        """

    def testRequest(self):
        """Test Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
