# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates insights from data based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import datetime
import unittest

import chartgpt_client
from chartgpt_client.models.api_request_ask_chartgpt200_response import \
    ApiRequestAskChartgpt200Response  # noqa: E501
from chartgpt_client.rest import ApiException


class TestApiRequestAskChartgpt200Response(unittest.TestCase):
    """ApiRequestAskChartgpt200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiRequestAskChartgpt200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ApiRequestAskChartgpt200Response`
        """
        model = chartgpt_client.models.api_request_ask_chartgpt200_response.ApiRequestAskChartgpt200Response()  # noqa: E501
        if include_optional :
            return ApiRequestAskChartgpt200Response(
                id = '', 
                created_at = 56, 
                finished_at = 56, 
                status = 'succeeded', 
                messages = [
                    chartgpt_client.models.response_messages_inner.Response_messages_inner(
                        id = '', 
                        created_at = 56, 
                        content = '', 
                        role = 'system', )
                    ], 
                dataset_id = '', 
                attempts = [
                    chartgpt_client.models.attempt.Attempt(
                        index = 56, 
                        created_at = 56, 
                        outputs = [
                            chartgpt_client.models.output.Output(
                                index = 56, 
                                created_at = 56, 
                                description = '', 
                                type = '', 
                                value = '', )
                            ], 
                        errors = [
                            chartgpt_client.models.error.Error(
                                index = 56, 
                                created_at = 56, 
                                type = '', 
                                value = '', )
                            ], )
                    ], 
                output_type = 'any', 
                outputs = [
                    chartgpt_client.models.output.Output(
                        index = 56, 
                        created_at = 56, 
                        description = '', 
                        type = '', 
                        value = '', )
                    ], 
                errors = [
                    chartgpt_client.models.error.Error(
                        index = 56, 
                        created_at = 56, 
                        type = '', 
                        value = '', )
                    ], 
                usage = chartgpt_client.models.response_usage.Response_usage(
                    tokens = 56, )
            )
        else :
            return ApiRequestAskChartgpt200Response(
        )
        """

    def testApiRequestAskChartgpt200Response(self):
        """Test ApiRequestAskChartgpt200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
