# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates charts and SQL queries based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import chartgpt_client
from chartgpt_client.models.api_request_ask_chartgpt_request import ApiRequestAskChartgptRequest  # noqa: E501
from chartgpt_client.rest import ApiException

class TestApiRequestAskChartgptRequest(unittest.TestCase):
    """ApiRequestAskChartgptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiRequestAskChartgptRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiRequestAskChartgptRequest`
        """
        model = chartgpt_client.models.api_request_ask_chartgpt_request.ApiRequestAskChartgptRequest()  # noqa: E501
        if include_optional :
            return ApiRequestAskChartgptRequest(
                prompt = 'Plot the average APR for the ***REMOVED*** protocol in the past 6 months.', 
                dataset_id = '', 
                output_type = 'chart', 
                max_outputs = 56, 
                max_attempts = 56, 
                max_tokens = 56, 
                stream = True
            )
        else :
            return ApiRequestAskChartgptRequest(
        )
        """

    def testApiRequestAskChartgptRequest(self):
        """Test ApiRequestAskChartgptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
