# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates charts and SQL queries based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.api_sql_generate_sql200_response import ApiSqlGenerateSql200Response  # noqa: E501
from openapi_client.rest import ApiException

class TestApiSqlGenerateSql200Response(unittest.TestCase):
    """ApiSqlGenerateSql200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiSqlGenerateSql200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSqlGenerateSql200Response`
        """
        model = openapi_client.models.api_sql_generate_sql200_response.ApiSqlGenerateSql200Response()  # noqa: E501
        if include_optional :
            return ApiSqlGenerateSql200Response(
                query = ''
            )
        else :
            return ApiSqlGenerateSql200Response(
        )
        """

    def testApiSqlGenerateSql200Response(self):
        """Test ApiSqlGenerateSql200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
