# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates insights from data based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chartgpt_client
from chartgpt_client.api.chat_api import ChatApi  # noqa: E501
from chartgpt_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = chartgpt_client.api.chat_api.ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ask_chartgpt_stream_v1_ask_chartgpt_stream_post(self):
        """Test case for ask_chartgpt_stream_v1_ask_chartgpt_stream_post

        Ask Chartgpt Stream  # noqa: E501
        """
        pass

    def test_ask_chartgpt_v1_ask_chartgpt_post(self):
        """Test case for ask_chartgpt_v1_ask_chartgpt_post

        Ask Chartgpt  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
