# coding: utf-8

"""
    ChartGPT API

    The ChartGPT API is a REST API that generates charts and SQL queries based on natural language questions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chartgpt_client
from chartgpt_client.api.default_api import DefaultApi  # noqa: E501
from chartgpt_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = chartgpt_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_chart_generate_chart(self):
        """Test case for api_chart_generate_chart

        Generate a Plotly chart from a question  # noqa: E501
        """
        pass

    def test_api_sql_generate_sql(self):
        """Test case for api_sql_generate_sql

        Generate an SQL query from a question  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
