/**
 * ChartGPT API
 * The ChartGPT API is a REST API that generates insights from data based on natural language questions.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Output } from '../models/Output';
import { HttpFile } from '../http/http';

/**
* Attempt
*/
export class Attempt {
    /**
    * The timestamp of when the attempt was created.
    */
    'createdAt'?: number;
    /**
    * The errors of the attempt.
    */
    'errors'?: Array<Error>;
    /**
    * The index of the attempt.
    */
    'index'?: number;
    /**
    * The outputs of the attempt.
    */
    'outputs'?: Array<Output>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Error>",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<Output>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Attempt.attributeTypeMap;
    }

    public constructor() {
    }
}

