/**
 * ChartGPT API
 * The ChartGPT API is a REST API that generates insights from data based on natural language questions.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Output
*/
export class Output {
    /**
    * The timestamp of when the output was created.
    */
    'createdAt'?: number;
    /**
    * The description of the output.
    */
    'description'?: string;
    /**
    * The index of the output.
    */
    'index'?: number;
    /**
    * The type of the output.
    */
    'type'?: string;
    /**
    * The value of the output.
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Output.attributeTypeMap;
    }

    public constructor() {
    }
}

