/**
 * ChartGPT API
 * The ChartGPT API is a REST API that generates insights from data based on natural language questions.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from '../models/Message';
import { OutputType } from '../models/OutputType';
import { HttpFile } from '../http/http';

/**
* Request
*/
export class Request {
    /**
    * The data source URL based on which the response will be generated. The entity is optional. If not specified, the default data source will be used.
    */
    'dataSourceUrl'?: string;
    /**
    * The maximum number of attempts to generate an output.
    */
    'maxAttempts'?: number;
    /**
    * The maximum number of outputs to generate.
    */
    'maxOutputs'?: number;
    /**
    * The maximum number of tokens to use for generating an output.
    */
    'maxTokens'?: number;
    /**
    * The messages based on which the response will be generated.
    */
    'messages'?: Array<Message>;
    'outputType'?: OutputType;
    /**
    * The session ID of the request.
    */
    'sessionId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataSourceUrl",
            "baseName": "data_source_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxAttempts",
            "baseName": "max_attempts",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxOutputs",
            "baseName": "max_outputs",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxTokens",
            "baseName": "max_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<Message>",
            "format": ""
        },
        {
            "name": "outputType",
            "baseName": "output_type",
            "type": "OutputType",
            "format": ""
        },
        {
            "name": "sessionId",
            "baseName": "session_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Request.attributeTypeMap;
    }

    public constructor() {
    }
}



